### PR TITLE
Use jupytext paired notebooks

### PR DESCRIPTION
**Pull request by ar-jan**
I'd like to propose using [jupytext](https://github.com/mwouts/jupytext) paired notebooks. This allows to have diffable `py:percent` encoded `.py` scripts under version control, which can be kept in sync with the `.ipynb` notebooks (bi-directional). (Actually I would have liked to use only `py:percent` files, these can be opened in Jupyter Lab as well as directly in VSCode as runnable cells, but unfortunately Google Colab does not open them, and storing cell outputs is not possible in that format.)

It looks like the notebooks under `lessons` do not store any cell outputs, while the `solutions` ones do. Is that correct? I've assumed so, so I deleted the lesson notebooks only. They can be re-created by using `jupytext --sync`.

If we do this and merge it before #10, that PR can be updated with jupytext and reviewed more easily.

Pair all notebooks globally:

``` toml
# pyproject.toml
[tool.jupytext]
formats = "ipynb,py:percent"
```

Create `py:percent` .py files:

``` sh
jupytext --sync lessons/*.ipynb
jupytext --sync solutions/*.ipynb
rm -f lessons/*.ipynb
```

Compare with jupytext-converted release branch:
```
git diff feature/jupytext..release/2023-11-jupytext -- '*.py'
```

```
# Re-create the .ipynb files:
jupytext --sync lessons/*.py
```

The solutions `*.ipynb` files  have been reformatted by this operation but are functionally unchanged. I think the pretty format is preferable anyway.

### CODE REVIEW

**Review by jgonggrijp — COMMENTED** [review]
After #11 there will be another pull request to finally bring the repo up to date, i.e., with the course materials as they ended up being after the May 2024 edition. I am in favor of easier reviews in principle, but can we arrange all the logistics in such a way that I don't need to spend a lot of time converting notebooks from one format to another?

I should add that I'm actually not a regular JuPyteR notebook user. I never run it locally, so I'm a complete beginner when it comes to doing a conversion like this and verifying the result.

**Comment by ar-jan** [comment]
A next PR based on existing files would need to do the conversion as I describe here, but it takes no more than a few minutes. For the current PR I've already tested it locally to verify that it results in usable diffs; I could also push that commit to #10 (or a separate branch?).

I think using jupytext means trusting that the `.ipynb` and `py:percent .py` formats conversions are equivalent. I have only used it a few times, but in my experience it is correct, so I don't think there's any need for verifying other than maybe opening a few notebooks. There may be some non-relevant differences in metadata properties. (On the other hand, not using jupytext currently means needing to review without any readable diff at all because the notebooks are minified, we'd have to open the old and new versions of all changed files side by side and compare entire files visually for what are actually minor changes of a few lines).

**Comment by ar-jan** [comment]
Here's a [diff between this branch and release/2023-11 with the jupytext conversion added](https://github.com/CentreForDigitalHumanities/programming-in-python/compare/feature/jupytext..release/2023-11-jupytext).

**Comment by jgonggrijp** [comment]
Thanks for that diff, it's very convincing. I think jupytext would help not only for reviewing but also for authoring.

> It looks like the notebooks under `lessons` do not store any cell outputs, while the `solutions` ones do. Is that correct? I've assumed so, so I deleted the lesson notebooks only. They can be re-created by using `jupytext --sync`.

We generally keep the output out of the lessons because we want to demonstrate them in class. We do save the run output in the solutions modules (sometimes), but only to save the course participants some effort. I wouldn't actually mind to just keep only the `py:percent` files in git and accept that the participants have to run the cells themselves. In fact, I think I prefer that.

If Google Colab cannot open the jupytext files, this does rise the question how to combine this change with #12. Maybe we could set up a GitHub Actions pipeline that commits `.ipynb` files to a separate branch, every time we push to `main`?

@JeltevanBoheemen What do you think?

**Comment by JeltevanBoheemen** [comment]
The diff @ar-jan linked in a previous comment is 100% convincing enough to start using jupyter.
The small increase in overhead is not a big deal, it occurs once-twice every iteration of the course.

I would propose workin in the paired notebook format for now, for two reasons:
- As mentioned, Colab only runs `.ipynb`. The annoyance he developers feel over using Colab is overshadowed by the simplicity of sharing the notebooks with the participants. Until we find a better/different way to host/share the notebooks, we are thus bound to `.ipynb`
- The `.ipynb` format is **very** common these days, especially outside the "developer-sphere". I run into students all the time that have never engaged with Python without notebooks. The jupyter format is convenient for us, and also for those that would like to contribute to the course. But: for beginners wanting to self-pace the materials, or participants looking back, I think we should stick to the common format.

**Comment by JeltevanBoheemen** [comment]
Question: why remove the `lessons/*.ipynb` in this PR?
Could you not create a PR purely on the changes to `.py:percent` files, and then sync just before merging?
I would like to keep the `.ipynb` files accesible in the repo.

**Review by JeltevanBoheemen — APPROVED** [review]

**Comment by ar-jan** [comment]
We would use the .ipynb either way, the question is if we always check in both the .py and .ipynb to Git in the main/develop branches, or treat the .ipynb more like build artifacts and check them into branches like `release/2024-10` which are used by the students. The .ipynb can be recreated from the .py via the sync operation.

I like the idea to use .py as leading. Looks clean and makes future PRs (with only .py files to compare) simpler, and the .ipynb would still be made available via the release branches. But either way would be OK with me.

I would have deleted the .ipynb files in both directories, except it seemed like the notebook outputs being stored for solutions was deliberate. But @jgonggrijp thinks it's OK to have students have to run the cells (and that makes sense to me as well, since that should always work).

**Comment by JeltevanBoheemen** [comment]
Right, thanks for the explanation.

I argue (using the arguments from earlier comment) that we keep the `.ipynb` files available on `main`, so they are immediatly visible when someone visits the repository.

**Comment by ar-jan** [comment]
Alright, I've re-added `lessons/*.ipynb`.

**Pull request merged**
