### PR TITLE
2024-05

### PR DESCRIPTION
**Pull request by JeltevanBoheemen**

### CODE REVIEW

**Review by ar-jan — COMMENTED** [review]
@JeltevanBoheemen missing the solutions!

**Comment by JeltevanBoheemen** [comment]
Oh, right..

**Comment by jgonggrijp** [comment]
Ah, it appears you were able to download all notebooks from the May folder? I was just thinking I should probably prepare a pull request.

**Comment by JeltevanBoheemen** [comment]
> Ah, it appears you were able to download all notebooks from the May folder? I was just thinking I should probably prepare a pull request.

Yes, Edo shared the folder with me

**Review by ar-jan — APPROVED** [review]
The larger changes here are:

- Moves a section from `07 functions`  to `12 functions, bis`
- Adds to `09 string manipulation`
- Adds to ` 10 dictionaries`
- Removes obsolete section on iterables from `Tips` (covered in main lessons)

**Pull request merged**
